%% Correction of bias field (Intensity gradient) artificially generated by Microsoft Image Composite Editor (ICE)
%
%Author: Kun-Han (Tom) Lu
%Date: 04/10/2021
%Description: Microsoft's Image Composite Editor generates a bias field
%when performing image stitching on natural panorama images or microscopic
%images. This script correct for such intensity gradients in the final
%mosaic by preprocessing image tiles.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Main

%-- input directory that contains all image tiles
dir_parent = '.';

%-- load all image files in the directory
filePattern = fullfile([dir_parent,'/*.tif']);
tifFiles = dir(filePattern);

%-- sum image intensity across all tiles
for ii = 1 : length(tifFiles)
  img =imread([dir_parent,'/',tifFiles(ii).name]);
  img = mat2gray(img);
  if ii == 1
      imgsum = zeros(size(img));
  end
  if (size(img,1)==size(imgsum,1)&&size(img,2)==size(imgsum,2))
 	imgsum = imgsum+img;
  end
end

%-- lowpass filter
h = fspecial('average',100);
correctionImage = imfilter(imgsum,h,'replicate');

%-- normalize intensity [0 to 1]
correctionImage=correctionImage./max(max(correctionImage));

%-- make destination folder
savedir = [dir_parent,'/bias_field_correction'];
mkdir(savedir);

%-- then divide each frame by the correction image
for ii = 1 : length(tifFiles)
  img =imread([dir_parent,'/',tifFiles(ii).name]);
  img = mat2gray(img);
  if (size(img,1)==size(imgsum,1)&&size(img,2)==size(imgsum,2))
      correctedimg = img./correctionImage;
      correctedimg=correctedimg./max(max(correctedimg));
      correctedimg = uint8(255*correctedimg);
      imwrite(correctedimg,[savedir,'/',tifFiles(ii).name]);
  else
      imwrite(uint8(255*img),[savedir,'/',tifFiles(ii).name]);
  end
end